name: "Example action"

description: ""

inputs:
  param1:
    description: ""
    required: true
  param2:
    description: ""
    required: true
    default: ""
  param3:
    description: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Example task 1
      id: example-task-1
      run: |
        # Prepare a variable for output
        Write-Output "outputvar=$outputVar" >> $env:GITHUB_OUTPUT

      shell: pwsh

    - name: Upload modules to Azure storage
      run: |
        # Execute main function

        # Configure function params
        $params = @{
            param1= '${{ inputs.param1 }}'
            param2 = '${{ steps.example-task-1.outputs.outputVar }}'
            param3 = '${{ inputs.param2 }}'
        }

        # Dot source in all the functions in this action repo
        $functions = Get-ChildItem -Path '${{ github.action_path }}/powershell/functions' -Recurse -Filter "*.ps1"
        $functions | ForEach-Object {
          . $_.FullName
        }

        # Extract the main function and execute
        $mainFunction = Get-ChildItem -Path '${{ github.action_path }}/powershell/functions/main' -Filter "*.ps1"
        $mainFunctionBaseName = $mainFunction | Select-Object -ExpandProperty BaseName
        $output = & $mainFunctionBaseName @params -InformationAction Continue
        $output | ConvertTo-Json

      shell: pwsh

    - name: Clean up
      run: |
        # Clean up temp resources if needed

      shell: pwsh

branding:
  icon: "arrow-up-circle"
  color: "blue"
